FROM node:22.11.0-alpine3.20 AS builder

ARG APP_URL
ARG VITE_API_BASE_URL
ARG VITE_PUSHER_BEAMS_INSTANCE_ID
ARG VITE_PUSHER_APP_ID
ARG VITE_PUSHER_KEY
ARG VITE_PUSHER_SECRET
ARG VITE_PUSHER_CLUSTER
ARG VITE_TELEGRAM_BOT_NAME

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_PUSHER_BEAMS_INSTANCE_ID=$VITE_PUSHER_BEAMS_INSTANCE_ID
ENV VITE_PUSHER_APP_ID=$VITE_PUSHER_APP_ID
ENV VITE_PUSHER_KEY=$VITE_PUSHER_KEY
ENV VITE_PUSHER_SECRET=$VITE_PUSHER_SECRET
ENV VITE_PUSHER_CLUSTER=$VITE_PUSHER_CLUSTER
ENV VITE_TELEGRAM_BOT_NAME=$VITE_TELEGRAM_BOT_NAME

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:1.29.3-alpine3.22



WORKDIR /app

COPY --from=builder /app/dist /usr/share/nginx/html

COPY docker/nginx/conf.d/default.conf.example /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
