#!/usr/bin/env node
// Regenerates plugin-sdk/testing/*.generated.js (and plugin-sdk/template/manifest.generated.js) from the
// app's own src/pluginSystem sources, so the testing harness runs the exact same code the app runs.
// Run from the app repo only: `node plugin-sdk/testing/sync-prelude.mjs` (writes) or `--check` (verifies).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const here = dirname(fileURLToPath(import.meta.url));
const appSrc = join(here, '..', '..', 'src', 'pluginSystem');
const templateDir = join(here, '..', 'template');

const header = (from) =>
	`// Generated by plugin-sdk/testing/sync-prelude.mjs from ${from}.\n// Do not edit by hand: run \`node plugin-sdk/testing/sync-prelude.mjs\` from the app repo.\n`;

// CommonJS, not ESM: Jest (used by the app's own kitchen-sink test) cannot load real ESM without the
// --experimental-vm-modules flag, which this repo does not set. CommonJS still needs no build step for a
// plugin author, and Node's ESM loader can `import` a CommonJS module's named exports without any flag.
const transpile = (fileName) => {
	const source = readFileSync(join(appSrc, fileName), 'utf8');
	const { outputText } = ts.transpileModule(source, {
		fileName,
		compilerOptions: {
			module: ts.ModuleKind.CommonJS,
			target: ts.ScriptTarget.ES2020,
			esModuleInterop: true,
		},
	});
	return outputText.replace(
		/require\("\.\/(protocol|manifest|broker)"\)/g,
		'require("./$1.generated.js")',
	);
};

const extractConst = (source, name) => {
	const match = source.match(new RegExp(`const ${name} = [^;]+;`));
	if (!match) throw new Error(`${name} not found in sandbox.ts`);
	return match[0];
};

const extractPrelude = (source) => {
	const marker = 'export const PRELUDE = `';
	const start = source.indexOf(marker);
	if (start === -1) throw new Error('PRELUDE not found in sandbox.ts');
	const bodyStart = start + marker.length;
	const end = source.indexOf('`', bodyStart);
	if (end === -1) throw new Error('unterminated PRELUDE template literal in sandbox.ts');
	return source.slice(bodyStart, end);
};

const sandboxSource = readFileSync(join(appSrc, 'sandbox.ts'), 'utf8');

const manifestGenerated = header('src/pluginSystem/manifest.ts') + transpile('manifest.ts');

const outputs = new Map([
	[join(here, 'protocol.generated.js'), header('src/pluginSystem/protocol.ts') + transpile('protocol.ts')],
	[join(here, 'manifest.generated.js'), manifestGenerated],
	[join(here, 'broker.generated.js'), header('src/pluginSystem/broker.ts') + transpile('broker.ts')],
	[join(here, 'sandbox.generated.js'), header('src/pluginSystem/sandbox.ts') + transpile('sandbox.ts')],
	[join(here, 'uiTree.generated.js'), header('src/pluginSystem/uiTree.ts') + transpile('uiTree.ts')],
	[
		join(here, 'prelude.generated.js'),
		header('src/pluginSystem/sandbox.ts') +
			`${extractConst(sandboxSource, 'MAX_CALL_BYTES')}\n${extractConst(sandboxSource, 'MAX_RESULT_BYTES')}\nexport const PRELUDE = \`${extractPrelude(sandboxSource)}\`;\n`,
	],
	// A standalone copy so plugin-sdk/template validates a manifest with zero dependencies, even copied
	// out of this repo on its own.
	[join(templateDir, 'manifest.generated.js'), manifestGenerated],
]);

const check = process.argv.includes('--check');
const stale = [];
for (const [path, content] of outputs) {
	if (check) {
		let current = null;
		try {
			current = readFileSync(path, 'utf8');
		} catch {
			// missing file: treated as stale below
		}
		if (current !== content) stale.push(path);
	} else {
		writeFileSync(path, content);
	}
}

if (check) {
	if (stale.length) {
		console.error('Stale generated files, run `node plugin-sdk/testing/sync-prelude.mjs`:');
		stale.forEach((path) => console.error(` - ${path}`));
		process.exit(1);
	}
	console.log('plugin-sdk generated files are up to date.');
} else {
	console.log(`Synced ${outputs.size} generated files.`);
}
