name: Deploy CI
on:
  issue_comment:
    types: [created]
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  release:
    name: Deploy website
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && (contains(github.event.comment.body, 'Deploy') || contains(github.event.comment.body, 'deploy') || github.event_name == 'push' || github.event_name == 'pull_request')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
      - name: Install dependencies
        run: npm ci
      - name: Create .env
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build static site
        run: npm run build # Build your website
      - name: Install globally Surge
        run: npm install --global surge
      - name: Deploy
        uses: koj-co/deploy-pr-action@v1.0.1
        with:
          prefix: tmgr # Prefix for deployment URL
          robotsTxtPath: dist/spa/robots.txt # Add robots.txt file
          distDir: dist/spa # Path to dist directory
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # GitHub token
          SURGE_LOGIN: ${{ secrets.SURGE_EMAIL }} # Surge.sh email
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }} # Surge.sh token
